---
# file: site.yml
- hosts: web-servers
#  remote_user: glass

  tasks:
  #role:base
  - name: Install essential utils
    apt: name=nano,joe,git,vim,emacs,screen,tmux state=latest

  - name: Install build-essential
    apt: name=build-essential state=latest

  #role:web-servers
  - name: Install nginx
    apt: name=nginx state=latest

  - name: Configure nginx
    template: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf
    notify:
    - reload nginx

  #role:plug-website
  - name: Install jekyll
    apt: name=jekyll state=latest

  - name: Use Git to checkout latest plug website
    git: version="master" repo="https://github.com/plugorgau/plugorgau.github.io.git" dest="/home/glass/plugorgau.github.io/"
    

  - name: Reset permissions on plug website repo
    debug: msg="Not yet implemented"

  - name: Use Jekyll to build plug website
    debug: msg="Not yet implemented"

  - name: Use rsync destructively to update running site
    debug: msg="Not yet implemented"

  - name: Install nginx site config
    debug: msg="Not yet implemented"

  - name: Enable nginx site config
    debug: msg="Not yet implemented"

  #role: 

  #TODO: Move this to its own file
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
