---
# file: site.yml
- hosts: web-servers
#  remote_user: glass

  tasks:
  #role:base
  - name: Install essential utils
    apt: name={{ item }} state=latest
    with_items:
      - nano
      - joe
      - git
      - vim
      - emacs
      - screen
      - tmux
      - molly-guard
      - links

  - name: Set nano as default editor
    alternatives:
      name: editor
      path: /bin/nano

  - name: Install build-essential
    apt: name=build-essential state=latest

  #role:web-servers
  - name: Install nginx
    apt: name=nginx state=latest

  - name: Configure nginx
    template: src=nginx/nginx.conf dest=/etc/nginx/nginx.conf
    notify:
    - reload nginx

  - name: Configure default webpage
    template: src=nginx/default.html dest=/var/www/html/index.html

  #role:plug-website
  - name: Install jekyll
    apt: name=jekyll state=latest

  - name: Use Git to checkout latest plug website
    git: version="master" repo="https://github.com/plugorgau/plugorgau.github.io.git" dest="/home/glass/plugorgau.github.io/"
    become_user: glass
    register: plug_website_git

  - name: Use Jekyll to build plug website
    command: "jekyll build"
    args: 
      chdir: /home/glass/plugorgau.github.io/
    become_user: glass
    when: plug_website_git.changed
    register: plug_website_new_build

  - name: Use rsync + a script to destructively update running site
    shell: bash /home/glass/plugorgau.github.io/deploy.sh
    when: plug_website_new_build.changed

#  - name: Use rsync destructively to update running site
#    synchronize:
#      src: /home/glass/plugorgau.github.io/_site/
#      dest: /var/www/bayonet.plug.org.au/
#      delete: yes
#      recursive: yes
#    become_user: www-data
#    when: plug_website_new_build.changed

  - name: Install nginx site config
    template: 
      src: plug-website/plug.org.au.conf
      dest: /etc/nginx/sites-available/plug.org.au.conf
    notify: reload nginx

  - name: Enable nginx site config
    file:
      state: link 
      src: ../sites-available/plug.org.au.conf
      dest: /etc/nginx/sites-enabled/plug.org.au.conf
    notify: reload nginx

  #role: 

  #TODO: Move this to its own file
  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
